module.exports = {
  testEnvironment: "jsdom",
  testEnvironmentOptions: {
    customExportConditions: ["node", "node-addons"],
  },
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "babel-jest",
    "^@mui/x-charts(.*)$": "<rootDir>/node_modules/@mui/x-charts/index.js",
  },
  collectCoverage: true,
  collectCoverageFrom: [
    "**/*.{js,jsx}",
    "!**/out/**",
    "!**/src/*.{svg,ico,css}",
    "!**/extension/**",
    "!**/coverage/**",
    "!**/node_modules/**",
    "!**/.github/**",
    "!**/.next/**",
    "!**/.vscode/**",
    "!**/public/**",
    "!**/extension/**",
    "!**/*.config.{js,jsx}",
    "!**/lcov-report/**",
    "!**/.env/**",
    "!**/public/**",
    "!**/build/**",
    "!**/package.json/**",
    "!**/package-lock.json/**",
    "!**/reportWebVitals.js/**",
    "!**/setupTests.js/**",
  ],
  coverageThreshold: {
    global: {
      functions: 50,
      lines: 50,
      statements: -50,
    },
  },
  coverageDirectory: undefined,
};
