import * as React from "react";
import { styled } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Typography from "@mui/material/Typography";
import Paper from "@mui/material/Paper";
import Fab from "@mui/material/Fab";
import List from "@mui/material/List";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemText from "@mui/material/ListItemText";
import Avatar from "@mui/material/Avatar";
import Chip from "@mui/material/Chip";
import { Colors } from "../assets/colors";
import { FontSizes } from "../assets/fonts";
import { ListItemSecondaryAction } from "@mui/material";

const teamMembers = [
  {
    id: 1,
    firstName: "Brunch this week?",
    lastName: "Test",
    highestViolation:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    profilePicture: "/static/images/avatar/5.jpg",
    violationColor: Colors.ACCENT_COLOR_1,
  },
  {
    id: 2,
    firstName: "Birthday Gift",
    lastName: "Test",
    highestViolation: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
    profilePicture: "/static/images/avatar/1.jpg",
    violationColor: Colors.ACCENT_COLOR_2,
  },
  {
    id: 3,
    firstName: "Recipe to try",
    lastName: "Test",
    highestViolation:
      "I am try out this new BBQ recipe, I think this might be amazing",
    profilePicture: "/static/images/avatar/2.jpg",
    violationColor: Colors.ACCENT_COLOR_3,
  },
  {
    id: 4,
    firstName: "Yes!",
    lastName: "Test",
    highestViolation: "I have the tickets to the ReactConf for this year.",
    profilePicture: "/static/images/avatar/3.jpg",
    violationColor: Colors.ACCENT_COLOR_4,
  },
  {
    id: 5,
    firstName: "Doctor's Appointment",
    lastName: "Test",
    highestViolation:
      "My appointment for the doctor was rescheduled for next Saturday.",
    profilePicture: "/static/images/avatar/4.jpg",
    violationColor: Colors.ACCENT_COLOR_5,
  },
  {
    id: 6,
    firstName: "Discussion",
    lastName: "Test",
    highestViolation: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
    profilePicture: "/static/images/avatar/5.jpg",
    violationColor: Colors.ACCENT_COLOR_1,
  },
  {
    id: 7,
    firstName: "Summer BBQ",
    lastName: "Test",
    highestViolation: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
    profilePicture: "/static/images/avatar/1.jpg",
    violationColor: Colors.ACCENT_COLOR_2,
  },
];

export default function LeaderboardListeItem() {
  return (
    <React.Fragment>
      <CssBaseline />
      <Paper square sx={{ pb: "50px" }}>
        <List sx={{ mb: 2 }}>
          {teamMembers.map(
            ({
              id,
              firstName,
              lastName,
              highestViolation,
              profilePicture,
              violationColor,
            }) => (
              <React.Fragment key={id}>
                <ListItemButton>
                  <ListItemAvatar>
                    <Avatar alt={`${firstName}`} src={profilePicture} />
                  </ListItemAvatar>
                  <ListItemText
                    primary={`${firstName} ${lastName}`}
                    secondary={
                      <Chip
                        label={`${highestViolation}`}
                        sx={{
                          backgroundColor: violationColor,
                          color: Colors.TEXT_COLOR,
                          fontSize: FontSizes.captionFontSize,
                        }}
                      />
                    }
                  />
                  <ListItemSecondaryAction>
                    {" "}
                    <Chip
                      label="30"
                      sx={{
                        backgroundColor: violationColor,
                        color: Colors.TEXT_COLOR,
                        fontWeight: "bold",
                        fontSize: FontSizes.captionFontSize,
                      }}
                    />
                  </ListItemSecondaryAction>
                </ListItemButton>
              </React.Fragment>
            ),
          )}
        </List>
      </Paper>
    </React.Fragment>
  );
}
const StyledFab = styled(Fab)({
  position: "absolute",
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: "0 auto",
});
