name: Run all test and evaluate code coverage
run-name: branch testers
on: [push]
jobs:
   Functionalities:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: install packages
          run: npm install
        - name: install prettier
          run: npm install --save-dev --save-exact prettier
        - name: Ensure a consistent code style
          run: npx prettier . --write
        - name: Check if the files follow a consistent code style
          run: npx prettier --check .
        - name: install jest on github actions
          run: npm install --save-dev jest
        - name: Run All Test
          run:  npm run test