name: Run all test and evaluate code coverage
on: [push]
jobs:
   Example:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout repository
          run: actions/checkout@v2
        - name: install prettier
          run: npm install --save-dev --save-exact prettier
        - name: Ensure a consistent code style
          run: npx prettier . --write
        - name: Check if the files follow a consistent code style
          run: npx prettier --check .
        - name: install jest on github actions
          run: npm install --save-dev jest
        - name: Show all the files in that directory
          run: ls
        - name: Run All Test
          run: cd swearjar && npx jest .